### ISSUE TITLE
Download links in Wiki

### ISSUE THREAD

**Issue by pchaigno** [markdenihan/owaspSecurityShepherd#130]
Could you add links to the Shepherd Manual Pack Download in the Wiki? It's kind of hard to find if you land first on the GitHub repository. Also, should it be available with the [releases on GitHub](https://github.com/markdenihan/owaspSecurityShepherd/releases)?

**Comment by markdenihan** [comment]
Yes, it should! Added source forge links to the Wiki Home page and to the release page.

**Comment by pchaigno** [comment]
That was fast :zap:
