### ISSUE TITLE
Setup Tomcat over HTTPs Guide

### ISSUE THREAD

**Issue by markdenihan** [markdenihan/owaspSecurityShepherd#135]
We should have Tomcat Setup with HTTPs running with a self signed cert by default with the Downloadable VM. We should write this process into the Manual Pack Read Me and Wiki Entries. 

Guide should include, Creating Cert, Pointing Tomcat at Cert, Getting Tomcat to Redirect Requests to Secure Service

**Comment by ismisepaul** [comment]
Work in progress:
1) Create cert using Java
- $JAVA_HOME/bin/keytool -genkey -alias tomcat -keyalg RSA
2) Fill in details **need to consult on these detail - password, names etc.
this will create a file under /home/<user>/.keystore
3) Edit tomcat server.xml. Uncomment <Connector port="8443".... and make it look like below
    <Connector port="8443" protocol="org.apache.coyote.http11.Http11Protocol"
                maxThreads="150" SSLEnabled="true" scheme="https" secure="true" 
                keystoreFile="/home/pmccann/.keystore" keystorePass="passw0rd"
                clientAuth="false" sslProtocol="TLS"/>
4) Start TomCat and navigate to https://localhost:8443


TODO: Redirect to https, test on Shepherd VM and investigate certificate security - TLS1.2 etc.

**Comment by markdenihan** [comment]
Great Stuff Paul

If it helps here are the server.xml settings for using 443 and 80 instead of the alt ports:
```xml
     <Connector address="0.0.0.0" port="80" protocol="HTTP/1.1"
               connectionTimeout="20000"
               URIEncoding="UTF-8"
               redirectPort="443" />
     <Connector address="0.0.0.0" port="443" protocol="HTTP/1.1" SSLEnabled="true"
               maxThreads="150" scheme="https" secure="true"
               clientAuth="false" sslProtocol="TLS" keystoreFile="AbsolutePathToFile" keystorePass="passwordHere" keyAlias="tomcat"/>
```  

And this is the element you want to add to the end of the tomcat master web.xml webapp entry  

```xml
<security-constraint>
        <web-resource-collection>
                <web-resource-name>Entire Application</web-resource-name>
                <url-pattern>/*</url-pattern>
        </web-resource-collection>
        <user-data-constraint>
                <transport-guarantee>CONFIDENTIAL</transport-guarantee>
        </user-data-constraint>
</security-constraint>
```

**Comment by ismisepaul** [comment]
Updated the wiki. Where's the "Manual Pack Read Me"

**Comment by markdenihan** [comment]
Manual Pack Read Me is based on the wiki. Don't have one stored in the
repository. Perhaps there should be? You can download the pack from source
forge and check it out if you like!

**Comment by markdenihan** [comment]
Actually @ismisepaul, The readme is based a direct copy and paste of this wiki:

https://github.com/markdenihan/owaspSecurityShepherd/wiki/Manual-Shepherd-Set-Up-(Windows)

I think we should start including two readme files from V2.4 and after. Ubuntu/Windows Specific

**Comment by ismisepaul** [comment]
makes sense I'm going to close this issue and open a specific one for windows and updating the main wiki to include the windows link under set up
