### ISSUE TITLE
Rewrite XSS Detection Platform

### ISSUE THREAD

**Issue by markdenihan** [markdenihan/owaspSecurityShepherd#99]
Currently this functionality works very well, but it was highlighted over the LATAM ctf that if any stylesheet contexts are created in user input, the scanner will crash. This is an AntiSamy bug, that as of yet I have not been able to work around. 

It's in Shepherd's interests to abandon the AntiSamy platform it is currently using in place for one which is maintained, or for a homemade option.

**Comment by SeanDuggan** [comment]
Making a homemade filter would be fun!

**Comment by markdenihan** [comment]
Filters are easy. Comprehensive detection... it will be fun!

**Comment by markdenihan** [comment]
So Im looking into replacing antisamy with the Newer OWASP project; OWASP Java HTML sanitizer Project;

https://www.owasp.org/index.php/OWASP_Java_HTML_Sanitizer

**Comment by markdenihan** [comment]
So the Java HTML Sanitizer Project wouldn't fly. So I built a new homemade one which is outperforming the AntiSamy based detection on Unit Tests. AND it doesn't crash with there is a stylesheet context. Pretty Happy with it. Needs to be tested, so try out the CRAZIEST XSS strings you can in the XSS levels in any build after commit 9915d7f29034fffddbd0b38c2eca124a05fec976
